language: node_js
node_js:
- '8'
services:
- postgresql
before_script:
- psql -c 'CREATE DATABASE exoplanets_test;' -U postgres
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: n8zTRxEftDLedjiXg0Ug0jEyZrnGr1qbouq4jvGdPD6lH7DX9ICq5kiAsmiaMGffEo5mcbE7rLXAF/72ZyaC09et5BFdckUQ418lTLn6brWgVgYR4ENPIX8BQdtMO3OAA9A9huW5iLF4gcuEdZ9aiP/bnBsvEn8529Teo7YX0D9GpqFV99RENizyYb6Ro8+0tGDHoGEJFgpf1jMqDwly8uPRXTyJSQrAIFZvr1v1cuPoTx2lWeTeXDpu8X1IlJ7gWo4AXzlk5sHjSMhgRcFV+TP0rrULYOyrVtUQ1MZCoe/GinrGLJKWcFIXox7MvsVY12qbD60ziBKrXUcuFsGVL8TAlLONW6AYzOHLQoPFDAUsLvrbzeogpjHwENRRdg/YLRDgxPOlKRNUsvMflCqlBR4lLm/dD/VEKGruBEr3R05A6nDXPa0cPdb+bPLVMEYUNiQ/s2/yAaKi3msac7WRDHn14NIZi2hXqYWu73w8FG2pP7wxPFBkuaFnhEBtRpzQGX9dzatjtmlwWbAAnf7Qgtn5yCe7rKzs88udaI7MtxsxyJnA3de40DHXR88wXypvg4CJRTO/zlLgO9K74W0oZXkiNvAIjs1bmySfP+eamsvW2rJxD2ejrS8cLU5fCr90H6Uooyctv0fT12iCptrXCmpT44M+Co154bLWT9/2Vvc=
